### ISSUE TITLE
Reference error to CIEDE2000

### ISSUE THREAD

**Issue by ericmelse** [yuki-koyama/color-util#25]
Dear Yuki-Koyama,

Note that the link for your reference:

The correctness of the implementation is verified through the test dataset provided by Gaurav Sharma http://www2.ece.rochester.edu/~gsharma/ciede2000/.

is broken. It now is:

[https://hajim.rochester.edu/ece/sites/gsharma/ciede2000/](https://hajim.rochester.edu/ece/sites/gsharma/ciede2000/)

**Comment by yuki-koyama** [comment]
Thank you so much
